### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by daniele-zurico** [htdt/ng2-jspm#1]
Why you need to import in this way:
import {bootstrap, ComponentAnnotation as Component, ViewAnnotation as View, Injectable} from 'angular2/angular2';

and not:
import {Component, View, bootstrap} from 'angular2/angular2';

??

Thanks
Daniele.

**Comment by htdt** [comment]
http://blog.thoughtram.io/angular/2015/05/09/writing-angular-2-code-in-es5.html

> @ComponentAnnotation and @ViewAnnotation are really the annotations. @ Component and @ View are the decorators that use the annotations internally.

**Comment by daniele-zurico** [comment]
Ok But what I mean is : there's no way to write the code as described in the documentation (in ts): 
https://angular.io/docs/js/latest/guide/displaying-data.html
?

**Comment by htdt** [comment]
https://angular.io/docs/js/latest/guide/setup.html
also describes this difference. I use traceur in this setup, it requires annotations.

**Comment by daniele-zurico** [comment]
so you mean that for now we don't have any choice to do in different way?

**Comment by htdt** [comment]
Typescript compiler and Babel uses decorators. TS plugin for JSPM – https://github.com/frankwallis/plugin-typescript. As far as I know, the next jspm version will support TS out of the box.

**Comment by htdt** [comment]
@daniele-zurico here is typescript version with decorators https://github.com/htdt/ng2-jspm/tree/typescript

**Comment by daniele-zurico** [comment]
@htdt super good! Thanks!
Just one question, do you have any experience with dgeni?
